# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkout:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  
    
  build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build java project
        run: javac src/main/java/com/example/logic/*.java
        working-directory: ${{ github.workspace }}
      
  test:
    runs-on: ubuntu-latest
    needs: build
  
    steps:   
    - name: Build with Maven
      run: mvn verify

