# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Print current working directory
      run: pwd
    - name: List files in root directory
      run: ls -R
      working-directory: ${{ github.workspace }}

    - name: List files in src/main/java/com/example/logic directory
      run: ls -R src/main/java/com/example/logic
      working-directory: ${{ github.workspace }}

  build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
    - name: Print current working directory
      run: pwd
    - name: List files in root directory
      run: ls -R
      working-directory: ${{ github.workspace }}

    - name: List files in src/main/java/com/example/logic directory
      run: ls -R src/main/java/com/example/logic
      working-directory: ${{ github.workspace }}
   
    - name: Compile Java source files
      run: javac src/main/java/com/example/logic/*.java
      

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run Maven
      run: mvn -B package --file pom.xml
      
  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Generate report
      run: mvn site
      working-directory: ${{ github.workspace }}

